### PR TITLE
Add option to disable aot.c generation

### PR DESCRIPTION
**Pull request by adrianherrera**
Hello! Thanks for the great tool. Sometimes it is useful to use a custom main function, so I thought it would be useful to have an option to disable the generation of `aot.c`. Let me know what you think!

### CODE REVIEW

**Comment by tkuchta** [comment]
Hi @adrianherrera , thanks for the PR!
I think that the idea is good. However, there is one thing to consider: in addition to calling the function under test we also perform initialization of global variables in main. 
I was wondering if this could be more helpful in your scenario to keep the init of the globals, but skip the call to the function under test. 
If that is the case, we would need to change otgenerator.py -> _create_test_driver
Alternatively, we could also rename main to aot_main so that it doesn't collide (in case you would need to call the globals init from your main file).
Please let me know what you think.

**Comment by adrianherrera** [comment]
Hi @tkuchta,

Yeah okay, these are all good ideas.

I think maybe we can keep the init of globals, but not call any functions. Essentially, `main` almost becomes another stub that needs to be written.

If you're happy with that I'll modify the PR!

**Comment by tkuchta** [comment]
Hi @adrianherrera ,
Sounds great, thank you! It should be enough to skip the generation of the "call site" for the target function.

**Comment by adrianherrera** [comment]
Hey @tkuchta,

Sorry about the long delay! I've finally got a chance to make the change to the original PR. Now, rather than preventing the generation of `main`, it still generates `main` but no longer generates function calls.

Let me know what you think!

**Review by tkuchta — APPROVED** [review]

**Comment by tkuchta** [comment]
Hi @adrianherrera , thanks for the PR! It looks good and I think we can merge it

**Pull request merged**
